[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Configuration des formulaires Netlify
[forms]
  # Configuration globale pour tous les formulaires
  [forms.contact]
    # Email de notification pour les soumissions de formulaire
    to = "contact@domaine-dubraud.com"
    # Sujet de l'email
    subject = "Nouvelle demande de contact - Domaine de Dubraud"
    # Template de l'email (optionnel)
    template = "Nouvelle demande de contact reçue :\n\nNom: {{ name }}\nEmail: {{ email }}\nTéléphone: {{ phone }}\nService: {{ service }}\nType de demande: {{ requestType }}\n\nMessage:\n{{ message }}"

# Configuration du domaine personnalisé
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Force HTTPS redirect
[[redirects]]
  from = "http://domaine-dubraud.com/*"
  to = "https://domaine-dubraud.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.domaine-dubraud.com/*"
  to = "https://domaine-dubraud.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.domaine-dubraud.com/*"
  to = "https://domaine-dubraud.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
